import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import '@/styles/index.scss'
import ClientCommon from './ClientCommon'
import Header from '@/sections/Header'
import Footer from '@/components/Footer'

const poppins = Poppins({
  subsets: ['latin'],
  display: 'swap',
  weight: ['300', '400', '500', '600', '700'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <ClientCommon />
        <Header className="shadow-sm dark:border-b dark:border-neutral-700" />
        {children}
        <Footer />
      </body>
    </html>
  )
}
